apiVersion: v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        role: master
    spec:
      restartPolicy: Always
      containers:
        - image: epitechcontent/t-dop-600-worker:k8s
          name: worker
          resources:
            limits:
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: REDIS_HOST
              value: "0.0.0.0"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 80